[package]
name = "syrusakbary/sveltekit-private-46e"
version = "0.1.0"
description = "wasmer-tests/wasmer-edge-astro-sample website"

[dependencies]
"wasmer/static-web-server" = "*"

[fs]
public = "dist"
